# Generated by Django 4.1.3 on 2022-11-20 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='media/unidades', verbose_name='Imagen')),
                ('url', models.URLField(max_length=500, verbose_name='Url')),
                ('creado', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('actualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pagina | Unidad',
                'verbose_name_plural': 'Pagina | Unidades',
                'db_table': 'app_pagina_inicio_unidades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='InicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=500, verbose_name='Video del inicio')),
                ('section_img', models.ImageField(upload_to='media/inicio', verbose_name='Img del about del inicio')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del about del inicio')),
                ('descripcion', models.TextField(verbose_name='Texto del about del inicio')),
                ('creado', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('actualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden')),
                ('categorias', models.ManyToManyField(to='inicio.unidadesmodel')),
                ('noticia', models.ManyToManyField(to='noticias.noticiasmodel')),
            ],
            options={
                'verbose_name': 'Pagina | Inicio',
                'verbose_name_plural': 'Pagina | Inicio',
                'db_table': 'app_pagina_inicio',
                'ordering': ['orden'],
            },
        ),
    ]
