# Generated by Django 4.1.3 on 2022-11-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='img_content',
            field=models.ImageField(upload_to='inicio/banner/', verbose_name='Imagen del banner del inicio'),
        ),
    ]
