# Generated by Django 4.1.3 on 2022-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_homemodel_img_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='img_content',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/banner/', verbose_name='Imagen del banner del inicio'),
        ),
    ]
