# Generated by Django 4.1.3 on 2022-11-21 01:30

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(default='', max_length=300, verbose_name='Nombre(s) y Apellido(s)')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido(s)')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de ciudadania'), ('CE', 'Cédula de extranjería'), ('PEP', 'Permiso especial de permanencia'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('V', 'Visa'), ('PP', 'Pasaporte')], default='CC', max_length=50, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=100, verbose_name='Número de documento')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('role', models.CharField(choices=[('SU', 'Administrador'), ('ED', 'Editor'), ('US', 'Usuario'), ('UP', 'Usuario con privilegios')], default='US', max_length=20, verbose_name='Rol')),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('W', 'Mujer'), ('O', 'Otro')], default='O', max_length=20, verbose_name='Género')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es una persona activa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'apps_autenticacion_users_model',
                'ordering': ['order', 'id', 'last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
