# Generated by Django 4.1.3 on 2022-11-20 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/noticias', verbose_name='Imagen de presentación de la noticia')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción de la noticia')),
                ('creado', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de cración')),
                ('actualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pagina | Noticia',
                'verbose_name_plural': 'Pagina | Noticias',
                'db_table': 'app_pagina_noticia',
                'ordering': ['orden'],
            },
        ),
    ]
