# Generated by Django 4.1.3 on 2022-11-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_newsmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='home_active',
            field=models.BooleanField(default=True, verbose_name='Se muestra en el inicio'),
        ),
    ]
