# Generated by Django 4.1.3 on 2022-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_unitsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsmodel',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/unidades/', verbose_name='Logo'),
        ),
    ]
